# Create a post
POST http://localhost:3333/api/posts HTTP/1.1
Content-Type: application/json

{
  "authorId": "4d402196-c2d4-46f5-b274-933644968553",
  "origin": "CREATED",
  "status": "DRAFT",
  "tags": ["f28f0584-41ff-49ca-92a8-e88c101b81bc", "e492f3ec-a52e-45b6-9523-ea8685814714"],
  "postType": "TEXT",
  "title": "Sport Post title",
  "excerpt": "Short description text",
  "text": "Contents of the post"
}

###
# Repost post
POST http://localhost:3333/api/posts/repost/241c1498-c1b6-4256-af76-835dfd91c712 HTTP/1.1
Content-Type: application/json

{
  "newAuthorId": "new-c2d4-46f5-b274-933644968553"
}

###

# Update post
PUT http://localhost:3333/api/posts/29123f98-8f3a-4dc7-9d85-fc8077c00d91 HTTP/1.1
Content-Type: application/json

{
  "authorId": "4d402196-c2d4-46f5-b274-933644968553",
  "origin": "CREATED",
  "status": "DRAFT",
  "tags": ["id1"],
  "postType": "TEXT",
  "title": "Post title",
  "excerpt": "Short description text updated",
  "text": "Contents of the post updated"
}

###
# Delete By ID
DELETE http://localhost:3333/api/posts/e649ad34-4e69-4689-bd92-d78d75281a00 HTTP/1.1

###
# Get post by ID
GET http://localhost:3333/api/posts/97660e24-351f-46fd-b270-fe41fd61c2f7 HTTP/1.1

###
